project:
  type: website

website:
  title: "Andrew | Data Portfolio"
  navbar:
    background: "#2a4066"
    pinned: true
    left:
      - text: "Home"
        href: "index.qmd"
      - text: "Projects"
        href: "#projects-section"
      - text: "Contact"
        href: "contact.qmd"
  search: false  # Disables the search feature

format:
  html:
    include-in-header: custom-fonts.html
    theme: default
    css: "styles/landing.css"
    toc: false